### ISSUE TITLE
[MVP] Character Search endpoint

### ISSUE THREAD

**Issue by gltr** [HR-MMonster/mmonster#26]

**Comment by doctown** [comment]
<strong>Create a character profile</strong>
       Resolve nested objects
       -<em> Possible temp solution. Store them as STRING but they are actually JSONs</em>
<strong>Store the character profile in the database</strong>
<strong>Retrieve the character profile</strong>
<strong>Query character profiles</strong>
 <ul>Choose 2 - 4 query parameters (create documentation)
    <li> (1 - 2) parameters only on the character profile
     <em>  EX: Query results for all FF CPs</em></li>
    <li>(1 - 2) parameters on the character profile and the user of the profile
        <em>EX: Query results for all FF CPs that are available from 1am to 5am</em></li></ul>
